---
title: "Iteration and Listcols"
output: github_document
---

```{r set up, include = FALSE}  
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = '90%'
)

theme_set(theme_classic() + theme(legend.position = 'bottom'))

options(
  ggplot2.continous.colour = 'viridis_d',
  ggplot2.continous.fill = 'viridis_d'
)

scalr_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Lists 

You can put everything in list.

```{r}
l = list(
  vec_numeric = 5:8,
  vec_logical = c(TRUE, TRUE, FALSE, FALSE, FALSE),
  mat = matrix(1:8, nrow = 2, ncol = 4),
  summary = summary(rnorm(100))
)
```

```{r}
l
l$vec_numeric
l[[1]]
l[["vec_numeric"]]
l[["vec_numeric"]][1:3]
mean(l[["vec_numeric"]])
```

# 'for' loop

Create a new list.

```{r}
list_norm = 
  list(
    a = rnorm(20, mean = 3, sd = 1),
    b = rnorm(30, mean = 0, sd = 5),
    c = rnorm(40, mean = 10, sd = .2),
    d = rnorm(20, mean = -3, sd = 1)
  )
```

Pause and get my old function.

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)) {
    stop('Input must be numeric')
  }
  
  if(length(x) < 3) {
    stop("Input must have at least three numbers")
  }
  
tibble(
  mean = mean(x),
  sd = sd(x)
)
  
}
```

I can apply that function to each list element.

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

Let's use a for loop:

```{r}
output = vector('list', length = 4)

for (i in 1:4){
  
  output[[i]] = mean_and_sd(list_norm[[i]])
  
}
```

## Let's try map!

```{r}
output = map(list_norm, mean_and_sd)
output = map(list_norm, median)
```

```{r}
output = map_dbl(list_norm, median)  ## spit out a different type rather than list, but dbl can only be used in the single value
```

```{r}
output = map_df(list_norm, mean_and_sd, .id = "input") # this .id = "input" makes the id can also be spited out
```

